/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { OwnableStorage } from "./OwnableStorage";
export type { UUPSImplementation } from "./UUPSImplementation";
export type { UUPSProxyWithOwner } from "./UUPSProxyWithOwner";
