/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AbstractProxy } from "./AbstractProxy";
export type { UUPSImplementation } from "./UUPSImplementation";
export type { UUPSProxy } from "./UUPSProxy";
