version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/packages/builder"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    target-branch: "main"
    ignore:
      update-types: ["version-update:semver-major"]
      
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    target-branch: "main"
    ignore:
      update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-cannon"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    target-branch: "main"
    ignore:
      update-types: ["version-update:semver-major"]
