version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    target-branch: "main"
    ignore:
      update-types: ["version-update:semver-major"]
