version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/packages/builder"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    ignore:
      # Ignore major version updates
      - dependency-name: 'prod-deps'
        update-types: ["version-update:semver-major"]
      - dependency-name: 'dev-deps'
        update-types: ["version-update:semver-major"]
      # Ignore specific dependencies

      - dependency-name: 'chalk'
        versions: ['>= 4.1.2']
      
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    ignore:
      # Ignore major version updates
      - dependency-name: 'prod-deps'
        update-types: ["version-update:semver-major"]
      - dependency-name: 'dev-deps'
        update-types: ["version-update:semver-major"]
      # Ignore specific dependencies

      - dependency-name: 'chalk'
        versions: ['>= 4.1.2']
      - dependency-name: 'untildify'
        versions: ['>= 4.0.0']
      - dependency-name: 'commander'
        versions: ['>= 9.5.0']

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-cannon"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    ignore:
      # Ignore major version updates
      - dependency-name: 'prod-deps'
        update-types: ["version-update:semver-major"]
      - dependency-name: 'dev-deps'
        update-types: ["version-update:semver-major"]
      # Ignore specific dependencies

      - dependency-name: 'chalk'
        versions: ['>= 4.1.2']
