# .github/release.yml

changelog:
  exclude:
    labels:
      - wontfix
      - bad-errors
      - good-first-issue
  categories:
    - title: Breaking Changes 🛠
      labels:
        - release-major
        - breaking-changes
    - title: Exciting New Features 🎉
      labels:
        - release-minor
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - bug
    - title: Patches
      labels:
        - release-patch
    - title: Documentation Changes
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
