# .github/release.yml

changelog:
  exclude:
    labels:
      - wontfix
      - bad-errors
      - good-first-issue
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major-release
        - breaking-changes
    - title: Exciting New Features 🎉
      labels:
        - minor-release
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
