#:schema node_modules/wrangler/config-schema.json
name = "cannon"
compatibility_date = "2026-06-09"

[assets]
#build_command = "cd packages/website && pnpm run build"
directory = "./packages/website/out"
