name = "greeter"
version = "<%= package.version %>"
description = "Simple project to verify the functionality of cannon"
keywords = ["sample", "greeter"]

[var.main]
salt = "greeter"
msg = "Hello world!"

[deploy.library]
artifact = "Library"
value = "2929372"

[deploy.Greeter]
artifact = "Greeter"
args = ["<%= settings.msg %>"]
libraries.Library = "<%= contracts.library.address %>"
salt = "<%= settings.salt %>"
