/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import type { Provider, TransactionRequest } from '@ethersproject/providers';
import type { PromiseOrValue } from '../../../../../common';
import type {
  UUPSProxy,
  UUPSProxyInterface,
} from '../../../../../@synthetixio/core-contracts/contracts/proxy/UUPSProxy';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'firstImplementation',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'contr',
        type: 'address',
      },
    ],
    name: 'NotAContract',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error',
  },
  {
    stateMutability: 'payable',
    type: 'fallback',
  },
  {
    stateMutability: 'payable',
    type: 'receive',
  },
];

const _bytecode =
  '0x608060405234801561001057600080fd5b5060405161032f38038061032f833981810160405281019061003291906101e1565b600073ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff161415610099576040517fd92e233d00000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b6100ac8161014360201b6100471760201c565b6100ed57806040517f8a8b41ec0000000000000000000000000000000000000000000000000000000081526004016100e4919061021d565b60405180910390fd5b806100fc61015660201b60201c565b60000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050610238565b600080823b905060008111915050919050565b60007f32402780481dd8149e50baad867f01da72e2f7d02639a6fe378dbd80b6bb446e905090565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101ae82610183565b9050919050565b6101be816101a3565b81146101c957600080fd5b50565b6000815190506101db816101b5565b92915050565b6000602082840312156101f7576101f661017e565b5b6000610205848285016101cc565b91505092915050565b610217816101a3565b82525050565b6000602082019050610232600083018461020e565b92915050565b60e9806102466000396000f3fe608060405236601057600e6018565b005b60166018565b005b60006020605a565b90503660008037600080366000845af43d6000803e80600081146042573d6000f35b3d6000fd5b600080823b905060008111915050919050565b60006062608b565b60000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b60007f32402780481dd8149e50baad867f01da72e2f7d02639a6fe378dbd80b6bb446e90509056fea26469706673582212205c67b86aef7b23c2a22bba213e3c951e334697080b986001d24fa6989a3cd8ca64736f6c634300080b0033';

type UUPSProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UUPSProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UUPSProxy__factory extends ContractFactory {
  constructor(...args: UUPSProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    firstImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UUPSProxy> {
    return super.deploy(
      firstImplementation,
      overrides || {}
    ) as Promise<UUPSProxy>;
  }
  override getDeployTransaction(
    firstImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(firstImplementation, overrides || {});
  }
  override attach(address: string): UUPSProxy {
    return super.attach(address) as UUPSProxy;
  }
  override connect(signer: Signer): UUPSProxy__factory {
    return super.connect(signer) as UUPSProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UUPSProxyInterface {
    return new utils.Interface(_abi) as UUPSProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UUPSProxy {
    return new Contract(address, _abi, signerOrProvider) as UUPSProxy;
  }
}
