/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  AccessError,
  AccessErrorInterface,
} from "../../../../../@synthetixio/core-contracts/contracts/errors/AccessError";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "Unauthorized",
    type: "error",
  },
];

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202e0a17c5f4708b70138421bdab07f5ca3da7e214aebf05b9b279820d29424a8364736f6c634300080b0033";

type AccessErrorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AccessErrorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AccessError__factory extends ContractFactory {
  constructor(...args: AccessErrorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AccessError> {
    return super.deploy(overrides || {}) as Promise<AccessError>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AccessError {
    return super.attach(address) as AccessError;
  }
  override connect(signer: Signer): AccessError__factory {
    return super.connect(signer) as AccessError__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AccessErrorInterface {
    return new utils.Interface(_abi) as AccessErrorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AccessError {
    return new Contract(address, _abi, signerOrProvider) as AccessError;
  }
}
