/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import type { Provider, TransactionRequest } from '@ethersproject/providers';
import type { PromiseOrValue } from '../../../../../common';
import type {
  AddressError,
  AddressErrorInterface,
} from '../../../../../@synthetixio/core-contracts/contracts/errors/AddressError';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'contr',
        type: 'address',
      },
    ],
    name: 'NotAContract',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error',
  },
];

const _bytecode =
  '0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122078870ea85d6bd1d19329dd51de8479f51d3d3f2d427420e68b79e9f4278db10a64736f6c634300080b0033';

type AddressErrorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AddressErrorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AddressError__factory extends ContractFactory {
  constructor(...args: AddressErrorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AddressError> {
    return super.deploy(overrides || {}) as Promise<AddressError>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AddressError {
    return super.attach(address) as AddressError;
  }
  override connect(signer: Signer): AddressError__factory {
    return super.connect(signer) as AddressError__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AddressErrorInterface {
    return new utils.Interface(_abi) as AddressErrorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressError {
    return new Contract(address, _abi, signerOrProvider) as AddressError;
  }
}
