/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOwnable__factory } from "./IOwnable__factory";
export { IUUPSImplementation__factory } from "./IUUPSImplementation__factory";
