import { IChainData } from './types';

export const chains: IChainData[] = [
  {
    name: 'Ethereum Mainnet',
    chainId: 1,
    shortName: 'eth',
    chain: 'ETH',
    network: 'mainnet',
    networkId: 1,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpc: ['https://ethereum.publicnode.com', 'https://eth.llamarpc.com'],
    etherscanApi: 'https://api.etherscan.io/api',
    etherscanUrl: 'https://etherscan.io',
    faucets: [],
    infoURL: 'https://ethereum.org',
  },
  {
    name: 'Ethereum Testnet Görli',
    chainId: 5,
    shortName: 'gor',
    chain: 'ETH',
    network: 'goerli',
    networkId: 5,
    nativeCurrency: { name: 'Görli Ether', symbol: 'GOR', decimals: 18 },
    etherscanApi: 'https://api-goerli.etherscan.io/api',
    etherscanUrl: 'https://goerli.etherscan.io',
    rpc: ['https://ethereum-goerli.publicnode.com', 'https://rpc.ankr.com/eth_goerli'],
    faucets: ['https://goerli-faucet.slock.it/?address=${ADDRESS}', 'https://faucet.goerli.mudit.blog'],
    infoURL: 'https://goerli.net/#about',
  },
  {
    name: 'Ethereum Testnet Sepolia',
    chainId: 11155111,
    shortName: 'sep',
    chain: 'ETH',
    network: 'sepolia',
    networkId: 11155111,
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'SepoliaETH', decimals: 18 },
    etherscanApi: 'https://api-sepolia.etherscan.io/api',
    etherscanUrl: 'https://sepolia.etherscan.io',
    rpc: ['https://ethereum-sepolia.publicnode.com', 'https://rpc.sepolia.org', 'https://rpc2.sepolia.org'],
    faucets: ['https://faucet.sepolia.dev/', 'https://sepoliafaucet.net', 'https://grabteeth.xyz'],
    infoURL: 'https://sepolia.dev/',
  },
  {
    name: 'xDAI Chain',
    chainId: 100,
    shortName: 'xdai',
    chain: 'XDAI',
    network: 'mainnet',
    networkId: 100,
    nativeCurrency: { name: 'xDAI', symbol: 'xDAI', decimals: 18 },
    rpc: ['https://gnosis.publicnode.com', 'https://rpc.gnosischain.com'],
    etherscanApi: 'https://api.gnosisscan.io/api',
    etherscanUrl: 'https://gnosisscan.io',
    faucets: [],
    infoURL: 'https://forum.poa.network/c/xdai-chain',
  },
  {
    name: 'Fuse Mainnet',
    chainId: 122,
    shortName: 'fuse',
    chain: 'FUSE',
    network: 'mainnet',
    networkId: 122,
    nativeCurrency: { name: 'Fuse', symbol: 'FUSE', decimals: 18 },
    rpc: ['https://rpc.fuse.io'],
    faucets: [],
    infoURL: 'https://fuse.io/',
  },
  {
    name: 'Aurora Mainnet',
    chainId: 1313161554,
    shortName: 'aurora',
    chain: 'Aurora',
    network: 'mainnet',
    networkId: 1313161554,
    nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 24 },
    rpc: ['https://mainnet.aurora.dev'],
    faucets: [],
    infoURL: 'https://near.org/',
  },
  {
    name: 'Matic Mainnet',
    chainId: 137,
    shortName: 'matic',
    chain: 'Matic',
    network: 'mainnet',
    networkId: 137,
    nativeCurrency: { name: 'Matic', symbol: 'MATIC', decimals: 18 },
    etherscanApi: 'https://api.polygonscan.com/api',
    etherscanUrl: 'https://polygonscan.com',
    rpc: ['https://polygon-bor.publicnode.com', 'https://polygon.llamarpc.com'],
    faucets: [],
    infoURL: 'https://matic.network/',
  },
  {
    name: 'Fantom Opera',
    chainId: 250,
    shortName: 'ftm',
    chain: 'FTM',
    network: 'mainnet',
    networkId: 250,
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
    rpc: ['https://fantom.publicnode.com', 'https://rpc.fantom.network'],
    faucets: [],
    infoURL: 'https://fantom.foundation',
  },
  {
    name: 'OP Mainnet',
    chainId: 10,
    shortName: 'oeth',
    chain: 'ETH',
    network: 'mainnet',
    networkId: 10,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    etherscanApi: 'https://api-optimistic.etherscan.io/api',
    etherscanUrl: 'https://optimistic.etherscan.io/',
    rpc: ['https://optimism.publicnode.com', 'https://optimism.llamarpc.com'],
    faucets: [],
    infoURL: 'https://optimism.io',
  },
  {
    name: 'OP Sepolia',
    chainId: 11155420,
    shortName: 'OP',
    chain: 'OP',
    network: 'testnet',
    networkId: 11155420,
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    rpc: ['https://optimism-sepolia.publicnode.com', 'https://rpc.ankr.com/optimism_sepolia'],
    etherscanApi: 'https://api-sepolia-optimistic.etherscan.io/api',
    etherscanUrl: 'https://sepolia-optimistic.etherscan.io/',
    faucets: [],
    infoURL: 'https://docs.optimism.io/chain/networks',
  },
  {
    name: 'OP Goerli',
    chainId: 420,
    shortName: 'OP',
    chain: 'OP',
    network: 'testnet',
    networkId: 420,
    nativeCurrency: { name: 'Ethereum', symbol: 'ETH', decimals: 18 },
    rpc: ['https://optimism-goerli.publicnode.com', 'https://rpc.ankr.com/optimism_testnet'],
    etherscanApi: 'https://api-goerli-optimism.etherscan.io/api',
    etherscanUrl: 'https://goerli-optimism.etherscan.io/',
    faucets: [],
    infoURL: 'https://docs.optimism.io/chain/networks',
  },
  {
    name: 'Binance Smart Chain Mainnet',
    chainId: 56,
    shortName: 'bnb',
    chain: 'BSC',
    network: 'mainnet',
    networkId: 56,
    nativeCurrency: {
      name: 'Binance Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
    rpc: [
      'https://bsc.publicnode.com',
      'https://binance.llamarpc.com',
      'https://bsc-dataseed.bnbchain.org',
      'https://bsc-dataseed1.bnbchain.org',
      'https://bsc-dataseed2.bnbchain.org',
      'https://bsc-dataseed4.bnbchain.org',
    ],
    faucets: [],
    infoURL: 'https://www.binance.org',
  },
  {
    name: 'Binance Smart Chain Testnet',
    chainId: 97,
    shortName: 'bnb',
    chain: 'BSC',
    network: 'Chapel',
    networkId: 97,
    nativeCurrency: {
      name: 'Binance Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
    rpc: [
      'https://bsc-testnet.publicnode.com',
      'https://data-seed-prebsc-1-s2.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s1.bnbchain.org:8545',
    ],
    faucets: ['https://testnet.binance.org/faucet-smart'],
    infoURL: 'https://testnet.binance.org/',
  },
  {
    name: 'Ethereum Classic Mainnet',
    chainId: 61,
    shortName: 'etc',
    chain: 'ETC',
    network: 'mainnet',
    networkId: 1,
    nativeCurrency: {
      name: 'Ethereum Classic Ether',
      symbol: 'ETC',
      decimals: 18,
    },
    rpc: ['https://etc.rivet.link', 'https://etc.etcdesktop.com'],
    faucets: [],
    infoURL: 'https://ethereumclassic.org',
  },
  {
    name: 'Ethereum Classic Testnet Mordor',
    chainId: 63,
    shortName: 'metc',
    chain: 'ETC',
    network: 'testnet',
    networkId: 7,
    nativeCurrency: {
      name: 'Mordor Classic Testnet Ether',
      symbol: 'METC',
      decimals: 18,
    },
    rpc: ['https://geth-mordor.etc-network.info', 'https://rpc.mordor.etccooperative.org'],
    faucets: [],
    infoURL: 'https://github.com/eth-classic/mordor/',
  },
  {
    name: 'Matic Mumbai',
    chainId: 80001,
    shortName: 'matic',
    chain: 'Matic',
    network: 'testnet',
    networkId: 80001,
    nativeCurrency: { name: 'Matic', symbol: 'MATIC', decimals: 18 },
    etherscanApi: 'https://api-testnet.polygonscan.com/api',
    etherscanUrl: 'https://mumbai.polygonscan.com/',
    rpc: ['https://polygon-mumbai-bor.publicnode.com', 'https://rpc.ankr.com/polygon_mumbai'],
    faucets: ['https://faucet.matic.network/'],
    infoURL: 'https://matic.network/',
  },
  {
    name: 'Celo Alfajores Testnet',
    chainId: 44787,
    shortName: 'ALFA',
    chain: 'CELO',
    network: 'alfajores',
    networkId: 44787,
    nativeCurrency: { name: 'Celo', symbol: 'CELO', decimals: 18 },
    rpc: ['https://alfajores-forno.celo-testnet.org', 'wss://alfajores-forno.celo-testnet.org/ws'],
    faucets: ['https://celo.org/developers/faucet', 'https://cauldron.pretoriaresearchlab.io/alfajores-faucet'],
    infoURL: 'https://docs.celo.org/',
  },
  {
    name: 'Celo',
    chainId: 42220,
    shortName: 'CELO',
    chain: 'CELO',
    network: 'celo',
    networkId: 42220,
    nativeCurrency: { name: 'Celo', symbol: 'CELO', decimals: 18 },
    rpc: ['https://forno.celo.org', 'https://rpc.ankr.com/celo'],
    faucets: [],
    infoURL: 'https://docs.celo.org/',
  },
  {
    name: 'Avalanche Mainnet C-Chain',
    chainId: 43114,
    shortName: 'AVAX',
    chain: 'AVAX',
    network: 'mainnet',
    networkId: 43114,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    etherscanApi: 'https://api.snowtrace.io/api',
    etherscanUrl: 'https://snowtrace.io/',
    rpc: ['https://avalanche-c-chain.publicnode.com', 'https://api.avax.network/ext/bc/C/rpc'],
    faucets: [],
    infoURL: 'https://docs.avax.network/',
  },
  {
    name: 'Avalanche FUJI C-Chain',
    chainId: 43113,
    shortName: 'FUJI',
    chain: 'AVAX',
    network: 'testnet',
    networkId: 43113,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    etherscanApi: 'https://api-testnet.snowtrace.io/api',
    etherscanUrl: 'https://testnet.snowtrace.io/',
    rpc: ['https://avalanche-fuji-c-chain.publicnode.com', 'https://api.avax-test.network/ext/bc/C/rpc'],
    faucets: [],
    infoURL: 'https://docs.avax.network/',
  },
  {
    name: 'Base Mainnet',
    chainId: 8453,
    shortName: 'basegor',
    chain: 'ETH',
    network: 'mainnet',
    networkId: 8453,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpc: ['https://mainnet.base.org', 'https://base.publicnode.com', 'https://base.llamarpc.com'],
    etherscanApi: 'https://api.basescan.org/api',
    etherscanUrl: 'https://basescan.org/',
    faucets: [],
    infoURL: 'https://base.org/',
  },
  {
    name: 'Base Sepolia Testnet',
    chainId: 84532,
    shortName: 'base-sepolia',
    chain: 'ETH',
    network: 'testnet',
    networkId: 84532,
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'sETH',
      decimals: 18,
    },
    rpc: ['https://sepolia.base.org', 'https://base-sepolia.publicnode.com'],
    etherscanApi: 'https://api-sepolia.basescan.org/api',
    etherscanUrl: 'https://sepolia.basescan.org/',
    faucets: ['https://www.coinbase.com/faucets/base-ethereum-sepolia-faucet'],
    infoURL: 'https://base.org/',
  },
  {
    name: 'Base Goerli Testnet',
    chainId: 84531,
    shortName: 'basegor',
    chain: 'ETH',
    network: 'mainnet',
    networkId: 84531,
    nativeCurrency: {
      name: 'Goerli Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    rpc: ['https://goerli.base.org', 'https://base-goerli.publicnode.com'],
    etherscanApi: 'https://api-goerli.basescan.org/api',
    etherscanUrl: 'https://goerli.basescan.org/',
    faucets: ['https://www.coinbase.com/faucets/base-ethereum-goerli-faucet'],
    infoURL: 'https://base.org/',
  },
  {
    name: 'Scroll',
    chainId: 534352,
    shortName: 'scroll',
    chain: '',
    network: 'mainnet',
    networkId: 534352,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpc: ['https://rpc.scroll.io', 'https://rpc.ankr.com/scroll'],
    etherscanApi: 'https://api.scrollscan.com/api',
    etherscanUrl: 'https://scrollscan.com',
    faucets: [],
    infoURL: 'https://scroll.io',
  },
  {
    name: 'Scroll Sepolia Testnet',
    chainId: 534351,
    shortName: 'scroll-sepolia',
    chain: '',
    network: 'testnet',
    networkId: 534351,
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'sETH', decimals: 18 },
    rpc: ['https://sepolia-rpc.scroll.io', 'https://rpc.ankr.com/scroll_sepolia_testnet'],
    etherscanApi: 'https://api-sepolia.scrollscan.com/api',
    etherscanUrl: 'https://sepolia.scrollscan.com',
    faucets: [],
    infoURL: 'https://scroll.io',
  },
  {
    name: 'Arbitrum One',
    chainId: 42161,
    shortName: 'arbitrum',
    chain: '',
    network: 'mainnet',
    networkId: 42161,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpc: ['https://arbitrum-one.publicnode.com', 'https://arbitrum.llamarpc.com', 'https://arb1.arbitrum.io/rpc'],
    etherscanApi: 'https://api.arbiscan.io/api',
    etherscanUrl: 'https://arbiscan.io',
    faucets: [],
    infoURL: 'https://arbitrum.io',
  },
  {
    name: 'Arbitrum Sepolia',
    chainId: 421614,
    shortName: 'arb-sepolia',
    chain: '',
    network: 'testnet',
    networkId: 421614,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpc: ['https://arbitrum-sepolia.publicnode.com', 'https://sepolia-rollup.arbitrum.io/rpc'],
    etherscanApi: 'https://api-sepolia.arbiscan.io/api',
    etherscanUrl: 'https://sepolia.arbiscan.io/',
    faucets: [],
    infoURL: 'https://arbitrum.io',
  },
];
