#:schema https://raw.githubusercontent.com/usecannon/cannon/refs/heads/dev/packages/lsp/src/schema.json
name = "greeter-foundry"
version = "1.2.3"
description = "Simple project to verify the functionality of cannon"
keywords = ["sample", "greeter"]

privateSourceCode = false

[var.main]
salt = "greeter"
msg = "my library was deployed in txn <%= contracts.library.deployTxnHash %>"

[deploy.library]
artifact = "Library"
value = "2929372"


[deploy.greeter]
artifact = "Greeter"
args = ["<%= settings.msg %>! call from signer <%= defaultSigner %>"]
libraries.Library = "<%= contracts.library.address %>"
salt = "<%= settings.salt %>"
