/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Library, LibraryInterface } from "../Library";

const _abi = [
  {
    inputs: [],
    name: "testLibraryFunction",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x610237610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100355760003560e01c8063f71c1efc1461003a575b600080fd5b610042610044565b005b6100826040518060400160405280601681526020017f546865206c696272617279206973206c6f6767696e6700000000000000000000815250610084565b565b61011a81604051602401610098919061017f565b6040516020818303038152906040527f41304fac000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff838183161783525050505061011d565b50565b60008151905060006a636f6e736f6c652e6c6f679050602083016000808483855afa5050505050565b6000610151826101a1565b61015b81856101ac565b935061016b8185602086016101bd565b610174816101f0565b840191505092915050565b600060208201905081810360008301526101998184610146565b905092915050565b600081519050919050565b600082825260208201905092915050565b60005b838110156101db5780820151818401526020810190506101c0565b838111156101ea576000848401525b50505050565b6000601f19601f830116905091905056fea2646970667358221220265dc65ee15f1e0d99a4f4931e9149d2fac47c4c132fbe6fcd40e9e430e58aad64736f6c63430008040033";

export class Library__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Library> {
    return super.deploy(overrides || {}) as Promise<Library>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Library {
    return super.attach(address) as Library;
  }
  connect(signer: Signer): Library__factory {
    return super.connect(signer) as Library__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibraryInterface {
    return new utils.Interface(_abi) as LibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Library {
    return new Contract(address, _abi, signerOrProvider) as Library;
  }
}
