/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errors from './errors';
export type { errors };
import type * as interfaces from './interfaces';
export type { interfaces };
import type * as ownership from './ownership';
export type { ownership };
import type * as proxy from './proxy';
export type { proxy };
