name: Build ethereum-optimism/supersim

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Custom ref tag or branch (optional)'
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: none
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository_owner }}/supersim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ethereum-optimism/supersim
          ref: ${{ github.event.inputs.ref || 'main' }}

      - name: Get supersim SHA
        id: supersim-sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.supersim-sha.outputs.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.ref || steps.supersim-sha.outputs.sha }}
