name: Upload Website to IPFS

on:
  workflow_dispatch:
    inputs:
      release_number:
        description: 'Release Tag (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  validate-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Validate release exists
        run: |
          RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.release_number }}")
          if [[ $(echo $RELEASE | jq -r '.message') == "Not Found" ]]; then
            echo "Error: Release ${{ github.event.inputs.release_number }} not found"
            exit 1
          fi
          echo "Release exists, proceeding with checkout"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_number }}
          
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20.5.1'

      - run: pnpm i --frozen-lockfile

      - run: echo "${{ vars.NEXT_ENV }}" > packages/website/.env.local
      - run: pnpm build:website

      - name: Create ZIP file
        run: zip -r "build-${{ github.event.inputs.release_number }}.zip" packages/website/out

      - name: Upload to Cannon Repo
        run: |
          curl -X POST \
            "https://repo.usecannon.com/api/v0/add?wrap-with-directory=true" \
            -H "Authorization: Bearer ${{ secrets.REPO_CANNON_JWT }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@build-${{ github.event.inputs.release_number }}.zip"

  

      
