name: Upload Website to IPFS

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Hash commit'
        required: true
        type: string

jobs:
  validate-and-upload:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_hash }}
          
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20.5.1'

      - run: pnpm i --frozen-lockfile

      - run: echo "${{ vars.NEXT_ENV }}" > packages/website/.env.local
      - run: pnpm run clean && pnpm -r --filter @usecannon/builder --filter @usecannon/cli --filter @usecannon/api --filter @usecannon/website run build

      - name: Create ZIP file
        run: |
          cd packages/website
          zip -r "../../build-${{ github.event.inputs.commit_hash }}.zip" out

      - name: Upload to Cannon Repo
        run: |
          curl -X POST \
            "https://repo.usecannon.com/api/v0/add?wrap-with-directory=true" \
            -H "Authorization: Bearer ${{ secrets.REPO_CANNON_JWT }}" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@build-${{ github.event.inputs.commit_hash }}.zip"