name: Upload Website to IPFS

on: workflow_dispatch

jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20.5.1'

      - run: pnpm i --frozen-lockfile
      - run: pnpm build

      - run: echo "${{ vars.NEXT_ENV }}" > packages/website/.env.local
      - run: cd packages/website && pnpm build

      - uses: dbeal-eth/ipfs-github-action@master
        id: ipfs
        with:
          path_to_add: packages/website/out
          cluster_host: ${{ secrets.IPFS_CLUSTER_ADDR }}
          cluster_user: ${{ secrets.IPFS_CLUSTER_USER }}
          cluster_password: ${{ secrets.IPFS_CLUSTER_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
